/home/cdr_admin/PondCDRSuite/cdr_sync/logs/*.log {
    daily
    rotate 3
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su cdr_admin cdr_admin
}

/home/cdr_admin/PondCDRSuite/cdr_sync/logs/*.json {
    daily
    rotate 3
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su cdr_admin cdr_admin
}
